# Generated by Django 4.0.3 on 2022-05-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информация',
            },
        ),
        migrations.CreateModel(
            name='Passajir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('data', models.DateTimeField(verbose_name='Дата регистрации')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('passport', models.IntegerField(verbose_name='Серия и номер паспорта')),
                ('srok', models.DateTimeField(verbose_name='Дата регистрации')),
                ('grajdanstvo', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
        migrations.CreateModel(
            name='Static',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='Пользователь (Купивший билет)')),
                ('firts_name', models.CharField(max_length=50, verbose_name='Фамилия, Имя пассажиров')),
                ('data', models.DateTimeField(verbose_name='Дата покупки')),
                ('vylet', models.CharField(max_length=50, verbose_name='Вылет (город)')),
                ('data_vyleta', models.DateTimeField(verbose_name='Вылет (дата и время')),
                ('port_vyleta', models.CharField(max_length=50, verbose_name='Вылет (аэропорт)')),
                ('prilet', models.CharField(max_length=50, verbose_name='Прилёт (город)')),
                ('data_prileta', models.DateTimeField(verbose_name='Прилёт (дата и время')),
                ('port_prileta', models.CharField(max_length=50, verbose_name='Прилёт (аэропорт)')),
                ('avia_comp', models.CharField(max_length=50, verbose_name='Авиакомпания')),
                ('col_pass', models.IntegerField(verbose_name='Количество пассажиров')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Статистику',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('data', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Notificet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст уведомления')),
                ('data', models.DateTimeField(verbose_name='Дата отправки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Обратная связь')),
                ('data_send', models.DateTimeField(verbose_name='Дата получение')),
                ('otvet', models.TextField(verbose_name='Ответ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
