# Generated by Django 4.0.3 on 2022-05-12 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passajir',
            name='passport',
            field=models.CharField(max_length=50, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='static',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Пользователь (Купивший билет)'),
        ),
    ]
