# Generated by Django 4.0.3 on 2022-05-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_static_data_prileta'),
    ]

    operations = [
        migrations.AddField(
            model_name='passajir',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
