# Generated by Django 4.0.3 on 2022-05-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_passajir_user_alter_users_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(verbose_name='Паспорт')),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('dr', models.TextField(verbose_name='День рождение')),
                ('nomer', models.TextField(verbose_name='Номер паспорта')),
                ('srok', models.TextField(verbose_name='Срок паспорта')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорты',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
