# Generated by Django 4.0.5 on 2022-06-27 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_passport_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='otvet',
            field=models.TextField(blank=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='passajir',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='dr',
            field=models.CharField(max_length=50, verbose_name='День рождение'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='img',
            field=models.CharField(max_length=50, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='nomer',
            field=models.CharField(max_length=50, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='srok',
            field=models.CharField(max_length=50, verbose_name='Срок паспорта'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='static',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Стоимость'),
        ),
    ]
