# Generated by Django 4.0.5 on 2022-06-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_feedback_otvet_alter_feedback_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='uid',
            field=models.CharField(default=123123123123123, max_length=100, verbose_name='UID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.users', verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='passajir',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='static',
            name='firts_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия, Имя пассажиров'),
        ),
    ]
