# Generated by Django 4.0.5 on 2022-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_users_uid_alter_notificet_user_alter_passajir_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UID'),
        ),
    ]
