# Generated by Django 4.0.5 on 2022-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_users_data_alter_users_name_alter_users_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='passajir',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='passajir',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='passajir',
            name='graj_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
