# Generated by Django 4.0.5 on 2022-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_passajir_category_alter_passajir_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
        migrations.AddField(
            model_name='notificet',
            name='see',
            field=models.CharField(blank=True, default='false', max_length=20, null=True, verbose_name='see'),
        ),
        migrations.AddField(
            model_name='users',
            name='lang',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Lang'),
        ),
    ]
