# Generated by Django 4.0.5 on 2022-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_errorapp_notificet_see_users_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus', models.CharField(max_length=50, verbose_name='Rus')),
                ('eng', models.CharField(max_length=50, verbose_name='Eng')),
                ('uz', models.CharField(max_length=50, verbose_name='Uz')),
                ('tj', models.CharField(max_length=50, verbose_name='Tj')),
                ('cn', models.CharField(max_length=50, verbose_name='Cn')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
