# Generated by Django 4.0.5 on 2022-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_citylang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citylang',
            name='cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cn'),
        ),
        migrations.AlterField(
            model_name='citylang',
            name='eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eng'),
        ),
        migrations.AlterField(
            model_name='citylang',
            name='rus',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rus'),
        ),
        migrations.AlterField(
            model_name='citylang',
            name='tj',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tj'),
        ),
        migrations.AlterField(
            model_name='citylang',
            name='uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uz'),
        ),
    ]
